version: "3"
services: 
    api: 
        build: ./api
        command: npm run start
        ports:
            - "3000:3000"
        environment: 
            - PORT=3000
            - HOST=http://realworld-docker.com
            - MONGO_URL=mongodb://api_db:27017/api
        depends_on: 
            - api_db
    auth: 
        build: ./auth
        command: npm run start
        ports:
            - "3001:3001"
        environment: 
            - PORT=3001
            - HOST=http://realworld-docker.com
            - MONGO_URL=mongodb://auth_db:27017/auth
        depends_on: 
            - auth_db                              
    api_db:
        image: mongo:latest
        container_name: realworld-docker-api
        volumes:
        - mongodb_api:/data/db
    auth_db:
        image: mongo:latest
        container_name: realworld-docker-auth
        volumes:
        - mongodb_auth:/data/db
volumes:
    mongodb_api:
    mongodb_auth: